
#
# 自定义网站的配置新鲜
#

# 网站名称（显示在标题中)
name: 随手记

# 简短的个人简介或说明（显示在标题中）
description: 不知则问，不能则学

# 头像
avatar: # https://avatars2.githubusercontent.com/u/29627730?s=460&u=80a11f1ed00701422eabaa9ed5e85c11adb61bae&v=4

# 您的网站网址 用于Sitemap.xml和您的RSS feed（例如http://barryclark.github.io或http://www.barryclark.co）
url: https://arvinzwt.github.io/

# 是否开启Google Analytics功能 如果开启，需要在/includes/analytics上修改配置
google_analytics: true

# 是否开启评论功能 如果开启，需要在/includes/gitalk上修改配置
gitalk: true

#
# !!您无需更改以下任何配置标志！
#

# 设置输出路径
permalink: /:title/

# 设置作者模块的输出
collections:
    authors:
        output: true

# 设置默认模板
defaults:
    - scope:
          path: ""
          type: "authors"
      values:
          layout: "author"
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
      values:
          layout: "default"

# 使用以下插件
plugins:
    - jekyll-sitemap # 使用官方的Jekyll网站地图gem创建网站地图
    - jekyll-feed # 使用官方的Jekyll feed宝石创建Atom feed
    - jekyll-seo-tag # 添加元标记以帮助SEO
    - jekyll-paginate # 分页插件

# 如果使用Sass @import语句，则需要确保将 sass_dir其设置为包含Sass文件的基本目录：
sass:
    sass_dir: _sass

# 分页
paginate: 20
paginate_path: "/blog/page:num/"

# 从生产_site排除这些文件
#exclude:
#    - Gemfile
#    - Gemfile.lock
#    - LICENSE
#    - README.md
#    - CNAME